### ISSUE TITLE
Make repo public

### ISSUE THREAD

**Issue by jamiecook** [vnopenroads/roads-cba-py#2]
When I transfered this in from my personal account i set it to private - now i need admin priveleges to make it public. 

@ngdnghia28  or @tailm1  can you help?

**Comment by jamiecook** [comment]
@ngdnghia28 - thanks for that - got it sorted. 
While I have you - do you know where details of the AWS logins etc for deploying are?

I'd like to spin up a AWS instance for deploying a flask/django app that wraps up that python code

**Comment by ngdnghia28** [comment]
@jamiecook I can access github only.

For other resources you should request @tailm1.
